### PR TITLE
support edit generate service type

### PR DESCRIPTION
**Pull request by kqzh**

### CODE REVIEW

**Review by MegaByte875 — COMMENTED** [review]
The chart nebulagraph need supported.

**Comment by kqzh** [comment]
> The chart nebulagraph need supported.



> The chart nebulagraph need supported.

ok

**Review by MegaByte875 — APPROVED** [review]
LGTM

**Comment by wey-gu** [comment]
Wow, now we have `.Values.nebula.graphd.serviceType` as configurations? COOL!

**Pull request merged**
