### PR TITLE
feat: e2e add zone

### PR DESCRIPTION
**Pull request by veezhang**
## What type of PR is this?
- [ ] bug
- [x] feature
- [ ] enhancement

### CODE REVIEW

**Comment by veezhang** [comment]
update version
```
--- PASS: TestNebulaCluster (1839.95s)
    --- SKIP: TestNebulaCluster/scale_with_default_values (0.00s)
    --- SKIP: TestNebulaCluster/update_version (0.00s)
    --- SKIP: TestNebulaCluster/update_resources (0.00s)
    --- SKIP: TestNebulaCluster/custom_config_for_static (0.00s)
    --- SKIP: TestNebulaCluster/custom_config_for_dynamic (0.00s)
    --- SKIP: TestNebulaCluster/custom_config_thrift_port_and_http_port (0.00s)
    --- SKIP: TestNebulaCluster/tools_for_exporter (0.00s)
    --- SKIP: TestNebulaCluster/scale_with_zone (0.00s)
    --- PASS: TestNebulaCluster/update_version_with_zone (1839.95s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Install_NebulaCluster (10.69s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Wait_NebulaCluster_to_be_ready (97.60s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Load_LDBC-SNB_dataset (116.97s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Upgrade_NebulaCluster_update_version (14.67s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_update_version (496.90s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Upgrade_NebulaCluster_update_version_with_scale (13.48s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_update_version_with_scale (899.98s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Upgrade_NebulaCluster_update_version_with_scale_and_enableForceUpdate (15.64s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_update_version_with_scale_and_enableForceUpdate (157.26s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Uninstall_NebulaCluster (12.10s)
PASS
```

**Comment by veezhang** [comment]
scale
```
--- PASS: TestNebulaCluster (658.40s)
    --- SKIP: TestNebulaCluster/scale_with_default_values (0.00s)
    --- SKIP: TestNebulaCluster/update_version (0.00s)
    --- SKIP: TestNebulaCluster/update_resources (0.00s)
    --- SKIP: TestNebulaCluster/custom_config_for_static (0.00s)
    --- SKIP: TestNebulaCluster/custom_config_for_dynamic (0.00s)
    --- SKIP: TestNebulaCluster/custom_config_thrift_port_and_http_port (0.00s)
    --- SKIP: TestNebulaCluster/tools_for_exporter (0.00s)
    --- PASS: TestNebulaCluster/scale_with_zone (658.39s)
        --- PASS: TestNebulaCluster/scale_with_zone/Install_NebulaCluster (9.85s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready (85.86s)
        --- PASS: TestNebulaCluster/scale_with_zone/Load_LDBC-SNB_dataset (116.92s)
        --- PASS: TestNebulaCluster/scale_with_zone/Upgrade_NebulaCluster_scale_out_[graphd,_storaged]:_4-3-4 (11.65s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_scale_out_[graphd,_storaged]:_4-3-4 (72.05s)
        --- PASS: TestNebulaCluster/scale_with_zone/Upgrade_NebulaCluster_scale_out__[graphd]:_5-3-4 (12.74s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_scale_out__[graphd]:_5-3-4 (79.25s)
        --- PASS: TestNebulaCluster/scale_with_zone/Upgrade_NebulaCluster_scale_out_[storaged]:_5-3-5 (11.48s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_scale_out_[storaged]:_5-3-5 (88.48s)
        --- PASS: TestNebulaCluster/scale_with_zone/Upgrade_NebulaCluster_scale_in_[graphd,_storaged]:_3-3-4 (13.33s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_scale_in_[graphd,_storaged]:_3-3-4 (44.68s)
        --- PASS: TestNebulaCluster/scale_with_zone/Upgrade_NebulaCluster_scale_in_[storaged]:_3-3-3 (11.11s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_scale_in_[storaged]:_3-3-3 (51.54s)
        --- PASS: TestNebulaCluster/scale_with_zone/Upgrade_NebulaCluster_scale_in[graphd]:_2-3-3 (11.37s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_scale_in[graphd]:_2-3-3 (23.96s)
        --- PASS: TestNebulaCluster/scale_with_zone/Uninstall_NebulaCluster (10.43s)
    --- SKIP: TestNebulaCluster/update_version_with_zone (0.00s)
PASS
```

**Comment by veezhang** [comment]
```
--- PASS: TestNebulaCluster (1346.67s)
    --- SKIP: TestNebulaCluster/scale_with_default_values (0.00s)
    --- SKIP: TestNebulaCluster/update_version (0.00s)
    --- SKIP: TestNebulaCluster/update_resources (0.00s)
    --- SKIP: TestNebulaCluster/custom_config_for_static (0.00s)
    --- SKIP: TestNebulaCluster/custom_config_for_dynamic (0.00s)
    --- SKIP: TestNebulaCluster/custom_config_thrift_port_and_http_port (0.00s)
    --- SKIP: TestNebulaCluster/tools_for_exporter (0.00s)
    --- PASS: TestNebulaCluster/scale_with_zone (429.30s)
        --- PASS: TestNebulaCluster/scale_with_zone/Install_NebulaCluster (0.31s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready (95.22s)
        --- PASS: TestNebulaCluster/scale_with_zone/Load_LDBC-SNB_dataset (105.02s)
        --- PASS: TestNebulaCluster/scale_with_zone/Upgrade_NebulaCluster_scale_out_[graphd,_storaged]:_4-3-4 (0.37s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_scale_out_[graphd,_storaged]:_4-3-4 (65.24s)
        --- PASS: TestNebulaCluster/scale_with_zone/Upgrade_NebulaCluster_scale_out__[graphd]:_5-3-4 (0.35s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_scale_out__[graphd]:_5-3-4 (40.27s)
        --- PASS: TestNebulaCluster/scale_with_zone/Upgrade_NebulaCluster_scale_out_[storaged]:_5-3-5 (0.38s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_scale_out_[storaged]:_5-3-5 (55.25s)
        --- PASS: TestNebulaCluster/scale_with_zone/Upgrade_NebulaCluster_scale_in_[graphd,_storaged]:_3-3-4 (0.38s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_scale_in_[graphd,_storaged]:_3-3-4 (25.20s)
        --- PASS: TestNebulaCluster/scale_with_zone/Upgrade_NebulaCluster_scale_in_[storaged]:_3-3-3 (0.37s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_scale_in_[storaged]:_3-3-3 (30.21s)
        --- PASS: TestNebulaCluster/scale_with_zone/Upgrade_NebulaCluster_scale_in[graphd]:_2-3-3 (0.38s)
        --- PASS: TestNebulaCluster/scale_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_scale_in[graphd]:_2-3-3 (10.18s)
        --- PASS: TestNebulaCluster/scale_with_zone/Uninstall_NebulaCluster (0.15s)
    --- PASS: TestNebulaCluster/update_version_with_zone (917.37s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Install_NebulaCluster (0.29s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Wait_NebulaCluster_to_be_ready (70.19s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Load_LDBC-SNB_dataset (95.02s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Upgrade_NebulaCluster_update_version (0.35s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_update_version (315.20s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Upgrade_NebulaCluster_update_version_with_scale (0.37s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_update_version_with_scale (280.24s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Upgrade_NebulaCluster_update_version_with_scale_and_enableForceUpdate (0.35s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Wait_NebulaCluster_to_be_ready_after_upgrade_update_version_with_scale_and_enableForceUpdate (155.20s)
        --- PASS: TestNebulaCluster/update_version_with_zone/Uninstall_NebulaCluster (0.13s)
PASS
```

**Review by MegaByte875 — APPROVED** [review]
LGTM

**Pull request merged**
